### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by yeroc** [subtlelib/poi#16]
It would be great if a new release were created to at least pick up the upgrade to POI 3.17.  Any chance of that anymore?

**Comment by serddmitry** [comment]
I'll see what I can do.

**Comment by maksimu** [comment]
Thank you for looking into this

**Comment by serddmitry** [comment]
Released a new version: https://github.com/subtlelib/poi/releases/tag/v.1.1.1

**Comment by yeroc** [comment]
@serddmitry Do you plan on publishing this release to Maven Central?

**Comment by yeroc** [comment]
@serddmitry Sorry, nevermind, I now see that the Maven coordinates were changed.  I know it's a hassle but it would be great to publish the [relocation information](https://maven.apache.org/guides/mini/guide-relocation.html) to Maven Central so that people are notified via Maven that they've moved.
